name: Restore, Build and Test the project

on:
  push:
    branches: 
    - develop
    - feature
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the app
      uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore the dependencies of the app
      run: dotnet restore
    - name: Build the app
      run: dotnet build --no-restore
    - name: Test the app
      run: dotnet test --no-build --verbosity normal
